mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

# REFERENCES
# Title: Writing your first Django app, part 2
# Author: Django Software Foundation and individual contributors
# Date: 2022
# Code version: 3.2
# URL: https://docs.djangoproject.com/en/3.2/intro/tutorial02/
# Software License: <license software is released under>


app_name = 'polls'
# url patterns for 'submit' and 'thoughts' are from Django tutorial
urlpatterns = [
    # ex: /polls/
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /polls/deepthoughts
    path('deepthoughts/', views.submit_thoughts.as_view(), name='submit'),
    # ex: /polls/deepthoughts/list
    path('deepthoughts/list/', views.thoughtsList.as_view(), name='thoughts')
]

polls/models.py
import datetime
from django.contrib import admin
from django.db import models
from django.utils import timezone

# REFERENCES
# Title: Writing your first Django app, part 2
# Author: Django Software Foundation and individual contributors
# Date: 2022
# Code version: 3.2
# URL: https://docs.djangoproject.com/en/3.2/intro/tutorial02/
# Software License: <license software is released under>

# Note the addition of import datetime and from django.utils import timezone,
# to reference Python’s standard datetime module
# and Django’s time-zone-related utilities in django.utils.timezone, respectively.


class Question(models.Model):
    question_text = models.CharField(max_length=200)  # creates a field of text in database
    pub_date = models.DateTimeField('date published')  # stores datetime object

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    #  A foreign key with cascade delete means that
    #  if a record in the parent table is deleted, then the corresponding records
    #  in the child table will automatically be deleted.
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # many-to-one relationship (Choice -> Question)
    choice_text = models.CharField(max_length=200)  # creates a field in database
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


# from Django tutorial
class Deepthought(models.Model):
    thought_text = models.CharField(max_length=200)

    def __str__(self):
        return self.thought_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Choice, Question, Deepthought

# REFERENCES
# Title: Writing your first Django app, part 2
# Author: Django Software Foundation and individual contributors
# Date: 2022
# Code version: 3.2
# URL: https://docs.djangoproject.com/en/3.2/intro/tutorial02/
# Software License: <license software is released under>
#
# Title: Django - Generic editing views
# Date: 2022
# Code Version: 4.0
# URL: https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/
# Software License: <>


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


# from Django's documentations on generic views
class submit_thoughts(generic.CreateView):
    template_name = 'polls/submit.html'
    model = Deepthought
    fields = ['thought_text']

    def get_success_url(self):
        return reverse('polls:thoughts')


# from Django tutorial
class thoughtsList(generic.ListView):
    template_name = 'polls/thoughts.html'
    context_object_name = 'thought_list'

    def get_queryset(self):
        return Deepthought.objects.all()

polls/templates/polls/detail.html
<!doctype html>
<!--
REFERENCES
Title: django-bootstrap-v5 Quickstart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <license software is released under>

Title: django-bootstrap-v5 QuickStart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <>

Title: Bootstrap Introduction
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/getting-started/introduction/
Software License: MIT

Title: Writing your first Django app, part 2
Author: Django Software Foundation and individual contributors
Date: 2022
Code version: 3.2
URL: https://docs.djangoproject.com/en/3.2/intro/tutorial02/
Software License: <>

Title: Bootstrap – Containers
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/layout/containers/
Software License: MIT

Title: Bootstrap – List Group
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/list-group/
Software License: MIT

Title: Bootstrap – Navs and tabs
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/navs-tabs/
Software License: MIT

Title: Bootstrap footer
Author: MD Bootstrap
Date: 2022
Code version: <>
URL: https://mdbootstrap.com/docs/b4/jquery/navigation/footer/
Software License: < >
-->

<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_messages %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'polls:index' %}">Polls</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Deep Thoughts</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'polls:submit' %}">Submit a thought</a>
                <a class="dropdown-item" href="{% url 'polls:thoughts' %}">Thought List</a>
            </div>
        </li>
    </ul>

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2022 Copyright: Richard He</div>
    </footer>

</div>

polls/templates/polls/index.html
<!doctype html>
<!--
REFERENCES
Title: django-bootstrap-v5 Quickstart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <license software is released under>

Title: django-bootstrap-v5 QuickStart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <>

Title: Bootstrap Introduction
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/getting-started/introduction/
Software License: MIT

Title: Writing your first Django app, part 2
Author: Django Software Foundation and individual contributors
Date: 2022
Code version: 3.2
URL: https://docs.djangoproject.com/en/3.2/intro/tutorial02/
Software License: <>

Title: Bootstrap – Containers
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/layout/containers/
Software License: MIT

Title: Bootstrap – List Group
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/list-group/
Software License: MIT

Title: Bootstrap – Navs and tabs
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/navs-tabs/
Software License: MIT

Title: Bootstrap footer
Author: MD Bootstrap
Date: 2022
Code version: <>
URL: https://mdbootstrap.com/docs/b4/jquery/navigation/footer/
Software License: < >
-->

<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_messages %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'polls:index' %}">Polls</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Deep Thoughts</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'polls:submit' %}">Submit a thought</a>
                <a class="dropdown-item" href="{% url 'polls:thoughts' %}">Thought List</a>
            </div>
        </li>
    </ul>

    <ol class="list-group list-group-numbered">
        <h3>A list of polls: </h3>
        {% if latest_question_list %}
            {% for question in latest_question_list %}
                <li class="list-group-item"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </ol>

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2022 Copyright: Richard He</div>
    </footer>

</div>

polls/templates/polls/results.html
<!doctype html>
<!--
REFERENCES
Title: django-bootstrap-v5 Quickstart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <license software is released under>

Title: django-bootstrap-v5 QuickStart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <>

Title: Bootstrap Introduction
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/getting-started/introduction/
Software License: MIT

Title: Writing your first Django app, part 2
Author: Django Software Foundation and individual contributors
Date: 2022
Code version: 3.2
URL: https://docs.djangoproject.com/en/3.2/intro/tutorial02/
Software License: <>

Title: Bootstrap – Containers
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/layout/containers/
Software License: MIT

Title: Bootstrap – List Group
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/list-group/
Software License: MIT

Title: Bootstrap – Navs and tabs
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/navs-tabs/
Software License: MIT

Title: Bootstrap footer
Author: MD Bootstrap
Date: 2022
Code version: <>
URL: https://mdbootstrap.com/docs/b4/jquery/navigation/footer/
Software License: < >
-->

<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_messages %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'polls:index' %}">Polls</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Deep Thoughts</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'polls:submit' %}">Submit a thought</a>
                <a class="dropdown-item" href="{% url 'polls:thoughts' %}">Thought List</a>
            </div>
        </li>
    </ul>

    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2022 Copyright: Richard He</div>
    </footer>

</div>

polls/templates/polls/submit.html
<!doctype html>
<!--
REFERENCES
Title: django-bootstrap-v5 Quickstart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <license software is released under>

Title: django-bootstrap-v5 QuickStart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <>

Title: Bootstrap Introduction
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/getting-started/introduction/
Software License: MIT

Title: Writing your first Django app, part 2
Author: Django Software Foundation and individual contributors
Date: 2022
Code version: 3.2
URL: https://docs.djangoproject.com/en/3.2/intro/tutorial02/
Software License: <>

Title: Bootstrap – Containers
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/layout/containers/
Software License: MIT

Title: Bootstrap – List Group
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/list-group/
Software License: MIT

Title: Bootstrap – Navs and tabs
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/navs-tabs/
Software License: MIT

Title: Bootstrap footer
Author: MD Bootstrap
Date: 2022
Code version: <>
URL: https://mdbootstrap.com/docs/b4/jquery/navigation/footer/
Software License: < >

Title: Bootstrap – Form Control
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/forms/form-control/
Software License: MIT

Title: Django Tutorial Part 9: Working with forms
Author: Mozilla and individual contributors
Date: 2022
Code version: <>
URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
Software License: open-source license
-->

<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_messages %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'polls:index' %}">Polls</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Deep Thoughts</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'polls:submit' %}">Submit a thought</a>
                <a class="dropdown-item" href="{% url 'polls:thoughts' %}">Thought List</a>
            </div>
        </li>
    </ul>

    <form action="{% url 'polls:submit' %}" method="post", class="form">
        {% csrf_token %}
        <label for="submit" class="form-label">Please enter a deep thought: </label>
        {{ form.as_p }}
        <input type="submit" class="form-text" id="submit">
    </form>

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2022 Copyright: Richard He</div>
    </footer>

</div>

polls/templates/polls/thoughts.html
<!doctype html>
<!--
REFERENCES
Title: django-bootstrap-v5 Quickstart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <license software is released under>

Title: django-bootstrap-v5 QuickStart
Author: Andre Bar'yudin
Date: 2020
Code version: e1787491
URL: https://django-bootstrap-v5.readthedocs.io/en/latest/quickstart.html
Software License: <>

Title: Bootstrap Introduction
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/getting-started/introduction/
Software License: MIT

Title: Writing your first Django app, part 2
Author: Django Software Foundation and individual contributors
Date: 2022
Code version: 3.2
URL: https://docs.djangoproject.com/en/3.2/intro/tutorial02/
Software License: <>

Title: Bootstrap – Containers
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/layout/containers/
Software License: MIT

Title: Bootstrap – List Group
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/list-group/
Software License: MIT

Title: Bootstrap – Navs and tabs
Author: Bootstrap team
Date: 2020
Code version: 5.0.2
URL: https://getbootstrap.com/docs/5.0/components/navs-tabs/
Software License: MIT

Title: Bootstrap footer
Author: MD Bootstrap
Date: 2022
Code version: <>
URL: https://mdbootstrap.com/docs/b4/jquery/navigation/footer/
Software License: < >
-->

<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_messages %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'polls:index' %}">Polls</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Deep Thoughts</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'polls:submit' %}">Submit a Thought</a>
                <a class="dropdown-item" href="{% url 'polls:thoughts' %}">Thought List</a>
            </div>
        </li>
    </ul>

    <ol class="list-group list-group-numbered">
        <h3>A list of deep thoughts: </h3>
        {% if thought_list %}
            {% for deepthought in thought_list %}
                <li class="list-group-item">{{ deepthought.thought_text }}</li>
            {% endfor %}
        {% else %}
            <p>There are no deep thoughts.</p>
        {% endif %}
    </ol>

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">© 2022 Copyright: Richard He</div>
    </footer>

</div>